{
 "title": "Monitoreo Sistema de Detección de Violencia",
 "time": { "from": "2023-09-18T09:30:49.000Z", "to": "2023-10-07T18:59:23.000Z" },
 "panels": [
  { "title": "Resultados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Valores",
   "type": "timeseries",
   "description": "Valores obtenidos por el modelo a partir de los datos de la cámara.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  valor_prediccion,\r\n  fecha\r\nFROM\r\n  (SELECT * FROM grafanadb.predicciones ORDER BY ID DESC LIMIT 10000) AS subquery\r\nORDER BY\r\n  ID ASC"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Predicción actual",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  valor_prediccion\r\nFROM\r\n  (SELECT * FROM grafanadb.predicciones ORDER BY ID DESC LIMIT 100) AS subquery\r\nORDER BY\r\n  ID ASC"
    }
   ]
  },
  {
   "type": "geomap",
   "description": "Ubicación del nodo IoT",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\nlatitud, longitud\r\nFROM\r\n  grafanadb.ubicaciones\r\nORDER BY\r\n  ID DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ubicación Geoespacial",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT latitud, longitud\r\nFROM grafanadb.ubicaciones\r\nORDER BY id DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Tiempo que tarda el sistema desde la toma de datos hasta el mensaje de alerta",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(fecha)\r\nAS\r\n  \"Last\"\r\nFROM\r\n  grafanadb.predicciones\r\nWHERE\r\n  ID = (SELECT MAX(ID) FROM grafanadb.predicciones)\r\nLIMIT\r\n  1"
    },
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(fecha)\r\nAS\r\n  \"Last2\"\r\nFROM\r\n  grafanadb.predicciones\r\nWHERE\r\n  ID = (SELECT MAX(ID) - 2 FROM grafanadb.predicciones)\r\nLIMIT\r\n  1"
    },
    { "expression": "$Last-$Last2", "type": "math" }
   ]
  },
  {
   "title": "Tiempo",
   "type": "timeseries",
   "description": "Gráfica del tiempo que se demora el sistema en hacer todo el procesamiento de los datos",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT UNIX_TIMESTAMP(fecha) AS LastA, fecha\r\nFROM grafanadb.predicciones\r\nWHERE fecha >= NOW() - INTERVAL 5 MINUTE\r\nORDER BY fecha DESC\r\nLIMIT 0, 1000"
    },
    {
     "dataset": "grafana",
     "rawSql": "SELECT UNIX_TIMESTAMP(fecha) AS LastB, fecha\r\nFROM grafanadb.predicciones\r\nWHERE fecha >= NOW() - INTERVAL 5 MINUTE\r\nORDER BY fecha DESC\r\nLIMIT 1, 1000"
    }
   ]
  },
  {
   "title": "Histograma",
   "type": "histogram",
   "description": "El histograma ayudará a entender cuál es la frecuencia de eventos de agresión",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 9 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT fecha, valor_prediccion\r\nFROM grafanadb.predicciones\r\nWHERE fecha >= NOW() - INTERVAL 1 DAY;"
    }
   ]
  },
  {
   "title": "Log de Errores",
   "type": "table",
   "description": "Revisar el estado de cada consulta ejecutada\nSe realizó: 1 (consulta exitosa)\nSe realizó: 0 (consulta no exitosa)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\nconsulta AS 'Error', \r\nfecha\r\nFROM\r\n  grafanadb.registro_consultas\r\nORDER BY\r\n  ID DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "title": "Monitoreo del sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"D:\" or r[\"device\"] == \"C:\" or r[\"device\"] == \"E:\" or r[\"device\"] == \"F:\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_steal\" or r[\"_field\"] == \"usage_nice\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "title": "Django", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  valor_prediccion\r\nFROM\r\n  (SELECT * FROM grafanadb.predicciones ORDER BY ID DESC LIMIT 100) AS subquery\r\nORDER BY\r\n  ID ASC"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_steal\" or r[\"_field\"] == \"usage_nice\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"D:\" or r[\"device\"] == \"C:\" or r[\"device\"] == \"E:\" or r[\"device\"] == \"F:\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"telegrafdb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}