# Generated by Django 4.2.5 on 2023-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Directorios',
                'verbose_name_plural': 'Directorios',
            },
        ),
    ]
