# Generated by Django 4.2.5 on 2023-09-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuraciones_del_sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_camera_address', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_option', models.CharField(blank=True, max_length=100, null=True)),
                ('local_camara', models.CharField(blank=True, max_length=100, null=True)),
                ('max_frames', models.CharField(blank=True, max_length=100, null=True)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'configuraciones del sistema',
                'verbose_name_plural': 'configuraciones del sistema',
            },
        ),
        migrations.CreateModel(
            name='configuraciones_generales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('acces_token_alert', models.CharField(blank=True, max_length=100, null=True)),
                ('acces_token_db', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=100, null=True)),
                ('base_de_datos', models.CharField(blank=True, max_length=100, null=True)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'configuraciones generales',
                'verbose_name_plural': 'configuraciones generales',
            },
        ),
    ]
