# Generated by Django 4.2.5 on 2023-09-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuraciones_del_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones_generales',
            name='ip_addr_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
