# Generated by Django 4.2.5 on 2023-09-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_configuraciones_generales_ip_addr_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directorios',
        ),
    ]
