# Generated by Django 4.2.5 on 2023-10-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_directorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciones_del_sistema',
            options={'verbose_name': 'Sistema', 'verbose_name_plural': 'Sistema'},
        ),
        migrations.AlterModelOptions(
            name='configuraciones_generales',
            options={'verbose_name': 'General', 'verbose_name_plural': 'General'},
        ),
    ]
