# Generated by Django 4.2.5 on 2023-10-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_configuraciones_generales_ip_addr_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='camara_fps',
            field=models.CharField(blank=True, choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='camera_option',
            field=models.CharField(blank=True, choices=[('0', 'Análoga'), ('1', 'Cámara IP'), ('2', 'Droidcam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='local_camara',
            field=models.CharField(blank=True, choices=[('0', 'Cámara 1'), ('1', 'Cámara 2'), ('2', 'Cámara 4'), ('3', 'Cámara 5'), ('4', 'Cámara 6'), ('5', 'Cámara 7'), ('6', 'Cámara 8'), ('7', 'Cámara 9'), ('8', 'Cámara 10')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='Interfaz',
            field=models.CharField(blank=True, choices=[('Wi-Fi', 'Wi-Fi'), ('Ethernet', 'Ethernet')], max_length=100, null=True, verbose_name='Interfaz de Red'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='acces_token_alert',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token del BOT de Alerta'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='acces_token_db',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token del BOT de Guardado'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='base_de_datos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Base de Datos'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Chat de Telegram'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña de la Base de Datos'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Host de la Base de Datos'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Mensaje de Telegram'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de la Base de Datos'),
        ),
    ]
