# Generated by Django 4.2.5 on 2023-10-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_configuraciones_del_sistema_camara_fps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='camara_fps',
            field=models.CharField(blank=True, choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=100, null=True, verbose_name='Frames por Segundo de la Cámara'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='ip_camera_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Cámara'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geolocalización: Latitud'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='local_camara',
            field=models.CharField(blank=True, choices=[('0', 'Cámara 1'), ('1', 'Cámara 2'), ('2', 'Cámara 4'), ('3', 'Cámara 5'), ('4', 'Cámara 6'), ('5', 'Cámara 7'), ('6', 'Cámara 8'), ('7', 'Cámara 9'), ('8', 'Cámara 10')], max_length=100, null=True, verbose_name='Número de Cámara Local'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geolocalización: Longitud'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='max_frames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Frames que se van a Procesar'),
        ),
        migrations.AlterField(
            model_name='configuraciones_generales',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
    ]
