# Generated by Django 4.2.5 on 2023-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_configuraciones_del_sistema_camara_fps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='camera_option',
            field=models.CharField(blank=True, choices=[('0', 'Análoga'), ('1', 'Cámara IP'), ('2', 'Droidcam')], max_length=100, null=True, verbose_name='Tipo de Cámara'),
        ),
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='ip_camera_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP de la Cámara'),
        ),
    ]
