# Generated by Django 4.2.5 on 2023-10-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_configuraciones_del_sistema_camera_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones_generales',
            name='canal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Canal de Telegram'),
        ),
    ]
