# Generated by Django 4.2.5 on 2023-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_configuraciones_generales_canal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones_del_sistema',
            name='camera_option',
            field=models.CharField(blank=True, choices=[('0', 'Conexión Directa'), ('1', 'Cámara IP'), ('2', 'Droidcam'), ('3', 'Video de Prueba')], max_length=100, null=True, verbose_name='Tipo de Cámara'),
        ),
    ]
